[package]
name = "educraft"
version = "0.4.1"
description = "EDUcraft - Cross-Platform Desktop Application"
authors = ["EDUcraft Contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
libdbus-sys = { version = "0.2", features = ["vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
